name: bookhub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.6

  font_awesome_flutter: ^9.1.0
  share_plus: ^2.1.4
  
  youtube_player_flutter: ^8.0.0
  google_fonts: ^2.1.0
  full_screen_image_null_safe: ^2.0.0
  firebase_storage: ^8.1.3
  image_picker: ^0.8.1+1
  cloud_firestore: ^2.2.2
  firebase_core: ^1.3.0
  transparent_image: ^2.0.0
  path: ^1.8.0
  syncfusion_flutter_pdfviewer: ^19.2.44-beta
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/homepage/Slider/
    - assets/homepage/Slider/Academics/
    - assets/homepage/Slider/Science/
    - assets/homepage/Slider/Programming/
    - assets/homepage/Slider/Python/
    - assets/homepage/Slider/SAT/
    - assets/Class/
    - assets/Class9/CE/
    - assets/Class10/CE/
    - assets/Class11/CE/
    - assets/Class12/CE/
    - assets/Class9/CE/C/
    - assets/Class9/CE/CF/
    - assets/Class11/CE/CHA/
    - assets/Class10/CE/CN/
    - assets/Class11/CE/CP/
    - assets/Class10/CE/DBMS/
    - assets/Class12/CE/DCCN/
    - assets/Class10/CE/EDC/
    - assets/Class9/CE/FDS/
    - assets/Class10/CE/MP/
    - assets/Class10/CE/OOPS/
    - assets/Class9/CE/WPD/
    - assets/Class12/CE/WDD/
    - assets/About/
    - assets/homepage/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
